test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,15 +14,6 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.10.12'  # Specify your Python version
-
-    - name: Test
-      run: |
-        # Add commands to run your tests
-
     - name: Deploy
       env:
         SSH_PRIVATE_KEY: ${{ secrets.EC2 }}
@@ -56,34 +47,51 @@ jobs:
             echo "Zip file not found."
         fi
 
+        ENDSSH
+        
+  run-django:
+    needs: build-and-deploy
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout Repository
+      uses: actions/checkout@v2
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.10.12'  # Specify your Python version
+      
+    - name: Start Server
+      env:
+        SSH_PRIVATE_KEY: ${{ secrets.EC2 }}
+        HOST: ${{ secrets.HOST }}
+        USER: ${{ secrets.USER }}
+      run: |
+        ssh -o StrictHostKeyChecking=no $USER@$HOST 'bash -s' <<'ENDSSH'
+
         # Activate virtual environment
         cd mysite
-        # for consol log
-        pwd
+        pwd # for consol log
         source vemysite/bin/activate
 
-        # # Run database migrations
-        # python3 manage.py migrate
-        # # start server
-        # python3 manage.py runserver 35.160.162.164:8000
+        # Run database migrations
+        python3 manage.py migrate
+        # start server
+        python3 manage.py runserver 35.160.162.164:8000
 
         ENDSSH
-  
-  # test-connection:
-  #   needs: build-and-deploy
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Check if Website is Reachable
-  #     env:
-  #       HOST: ${{ secrets.HOST }}
-  #     run: |
-  #       # use curl to sent http request
-  #       response=$(curl --silent --head --fail '$HOST':8000/network/)
+    
+    - name: Check if Website is Reachable
+      env:
+        HOST: ${{ secrets.HOST }}
+      run: |
+        # use curl to sent http request
+        response=$(curl --silent --head --fail '$HOST':8000/network/)
 
-  #       # Check the exit status of the curl command
-  #       if [ $? -eq 0 ]; then
-  #           echo "Website is reachable."
-  #       else
-  #           echo "Website is not reachable."
-  #       fi
+        # Check the exit status of the curl command
+        if [ $? -eq 0 ]; then
+            echo "Website is reachable."
+        else
+            echo "Website is not reachable."
+        fi
         
