test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,34 +56,34 @@ jobs:
             echo "Zip file not found."
         fi
 
-        # Activate virtual environment
-        cd mysite
-        # for consol log
-        pwd
-        source vemysite/bin/activate
+  #       # Activate virtual environment
+  #       cd mysite
+  #       # for consol log
+  #       pwd
+  #       source vemysite/bin/activate
 
-        # Run database migrations
-        python3 manage.py migrate
-        # start server
-        python3 manage.py runserver 35.160.162.164:8000
+  #       # Run database migrations
+  #       python3 manage.py migrate
+  #       # start server
+  #       python3 manage.py runserver 35.160.162.164:8000
 
-        ENDSSH
+  #       ENDSSH
   
-  test-connection:
-    needs: build-and-deploy
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check if Website is Reachable
-      env:
-        HOST: ${{ secrets.HOST }}
-      run: |
-        # use curl to sent http request
-        response=$(curl --silent --head --fail '$HOST':8000/network/)
+  # test-connection:
+  #   needs: build-and-deploy
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Check if Website is Reachable
+  #     env:
+  #       HOST: ${{ secrets.HOST }}
+  #     run: |
+  #       # use curl to sent http request
+  #       response=$(curl --silent --head --fail '$HOST':8000/network/)
 
-        # Check the exit status of the curl command
-        if [ $? -eq 0 ]; then
-            echo "Website is reachable."
-        else
-            echo "Website is not reachable."
-        fi
+  #       # Check the exit status of the curl command
+  #       if [ $? -eq 0 ]; then
+  #           echo "Website is reachable."
+  #       else
+  #           echo "Website is not reachable."
+  #       fi
         
